config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users

  resources :payments
  resources :receivables
  resources :save_moneys do
    resources :save_money_wallets
  end
end

app/models/save_money_wallet.rb
class SaveMoneyWallet < ApplicationRecord
  belongs_to :save_money

  validates :title, :value, :date, presence: true
end

app/controllers/save_money_wallets_controller.rb
# frozen_string_literal: true

class SaveMoneyWalletsController < ApplicationController
  before_action :set_save_money, only: %i[create edit update destroy]
  before_action :set_save_money_wallet, only: %i[edit update destroy]

  def new
    @save_money_wallet = @save_money.wallets.new
  end

  def create
    @save_money_wallet = @save_money.wallets.create(save_money_wallet_params)

    respond_to do |format|
      if @save_money_wallet.save
        format.html { redirect_to @save_money, notice: 'Save money wallet was successfully created.' }
        format.json { render :show, status: :created, location: @save_money_wallet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @save_money_wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @save_money_wallet.update(save_money_wallet_params)
        format.html { redirect_to @save_money, notice: 'Save money wallet was successfully updated.' }
        format.json { render :show, status: :ok, location: @save_money_wallet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @save_money_wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @save_money_wallet.destroy
    respond_to do |format|
      format.html { redirect_to save_moneys_url, notice: 'Save money wallet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_save_money
    @save_money = SaveMoney.where(user: current_user).find(params[:save_money_id])
  end

  def set_save_money_wallet
    @save_money_wallet = @save_money.wallets.find(params[:id])
  end

  def save_money_wallet_params
    params.require(:save_money_wallet).permit(:title, :description, :value, :date)
  end
end

app/helpers/save_money_wallets_helper.rb
module SaveMoneyWalletsHelper
end

app/views/save_money_wallets/_form.html.erb
<%= form_with(model: [@save_money, SaveMoneyWallet.new]) do |form| %>

  <div class="row">
    <div class="col-2">
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: "form-select"  %>
    </div>

    <div class="col-2">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description, class: "form-select"  %>
    </div>

    <div class="col-2">
      <%= form.label :value, style: "display: block" %>
      <%= form.number_field :value, step: 0.01, class: "form-control" %>
    </div>

    <div class="col-2">
      <%= form.label :date, style: "display: block" %>
      <%= form.date_field :date, class: "form-select"  %>
    </div>

    <div class="col-2 mt-4">
      <%= form.submit class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/save_money_wallets/_wallets.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Value</th>
    <th>Date</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
    <% @save_money.wallets.each do |wallet| %>
      <tr>
        <td><%= wallet.title %></td>
        <td><%= wallet.description %></td>
        <td><%= number_to_currency(wallet.value, unit: "R$ ") %></td>
        <td><%= wallet.date %></td>
        <td><%= link_to "Editar", edit_save_money_save_money_wallet_path(@save_money, wallet) %></td>
        <td><%= link_to "Deletar", [@save_money, wallet], method: :delete, data: {confirm: 'Tem certeza que deseja deletar esta carteira?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/save_money_wallets/edit.html.erb
<h1>Editar <%= @save_money_wallet.title %> </h1>

<%= simple_form_for([@save_money, @save_money_wallet]) do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :value %>
  <%= f.input :date, as: :date %>
  <%= f.button :submit %>
<% end %>
<%= link_to "Voltar", save_money_path(@save_money) %>

app/views/save_money_wallets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Save Money Wallets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Value</th>
      <th>Date</th>
      <th>User</th>
      <th>Save money</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @save_money_wallets.each do |save_money_wallet| %>
      <tr>
        <td><%= save_money_wallet.title %></td>
        <td><%= save_money_wallet.description %></td>
        <td><%= save_money_wallet.value %></td>
        <td><%= save_money_wallet.date %></td>
        <td><%= save_money_wallet.user_id %></td>
        <td><%= save_money_wallet.save_money_id %></td>
        <td><%= link_to 'Show', save_money_wallet %></td>
        <td><%= link_to 'Edit', edit_save_money_wallet_path(save_money_wallet) %></td>
        <td><%= link_to 'Destroy', save_money_wallet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Save Money Wallet', new_save_money_wallet_path %>

app/views/save_money_wallets/new.html.erb
<h1>New Save Money Wallet</h1>

<%= render 'form', save_money_wallet: @save_money_wallet %>

<%= link_to 'Back', save_moneys_path %>

app/views/save_money_wallets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @save_money_wallet.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @save_money_wallet.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @save_money_wallet.value %>
</p>

<p>
  <strong>Date:</strong>
  <%= @save_money_wallet.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @save_money_wallet.user_id %>
</p>

<p>
  <strong>Save money:</strong>
  <%= @save_money_wallet.save_money_id %>
</p>

<%= link_to 'Edit', edit_save_money_wallet_path(@save_money_wallet) %> |
<%= link_to 'Back', save_money_wallets_path %>