config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users

  resources :payments
  resources :receivables
  resources :save_moneys do
    resources :save_money_wallets
  end
end

app/models/receivable.rb
class Receivable < ApplicationRecord
  belongs_to :user

  default_scope { order(date: :asc) }

  validates :title, :value, :date, presence: true
end

app/controllers/receivables_controller.rb
class ReceivablesController < ApplicationController
  before_action :set_receivable, only: %i[ show edit update destroy ]

  # GET /receivables or /receivables.json
  def index
    receivables = Receivable.where(user: current_user)
    @calendar, @pagy, @receivables = pagy_calendar(receivables.reorder(date: :desc),
                                                year:  { size:  [1, 1, 1, 1], order: :desc },
                                                month: { size:  [0, 12, 12, 0], order: :desc, format: "%B" },
                                                pagy:  { items: 10 },
                                                )
  end

  # GET /receivables/1 or /receivables/1.json
  def show; end

  # GET /receivables/new
  def new
    @receivable = Receivable.new
  end

  # GET /receivables/1/edit
  def edit; end

  # POST /receivables or /receivables.json
  def create
    @receivable = Receivable.new(user_receivable_params)

    respond_to do |format|
      if @receivable.save
        format.html { redirect_to @receivable, notice: "Receivable was successfully created." }
        format.json { render :show, status: :created, location: @receivable }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @receivable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receivables/1 or /receivables/1.json
  def update
    respond_to do |format|
      if @receivable.update(receivable_params)
        format.html { redirect_to @receivable, notice: "Receivable was successfully updated." }
        format.json { render :show, status: :ok, location: @receivable }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @receivable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receivables/1 or /receivables/1.json
  def destroy
    @receivable.destroy
    respond_to do |format|
      format.html { redirect_to receivables_url, notice: "Receivable was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_receivable
    @receivable = Receivable.where(user: current_user).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def receivable_params
    params.require(:receivable).permit(:title, :description, :value, :date)
  end

  def user_receivable_params
    receivable_params.merge({ user: current_user })
  end

  def pagy_calendar_period(collection)
    return [Date.today.to_time, Date.today.to_time] if collection.empty?

    to_time = collection.minmax.map!(&:date)
    to_time.map { |time| time.to_time }.sort!
  end

  def pagy_calendar_filter(collection, from, to)
    collection.where(date: from.utc..to.utc)  # storage in UTC
  end
end

app/helpers/receivables_helper.rb
module ReceivablesHelper
end

app/views/receivables/_by_month.html.erb
<% @receivables.reverse_each do |receivable| %>
  <h4> <%= receivable.first.strftime("%B %Y") %> </h4>
  <table class="table">
    <tbody>
    <% receivable.last.each do |body| %>
      <tr>
        <td>
          <%= body.date.strftime("%d/%m") %>
        </td>
        <td>
          <%= body.title %>
        </td>
        <td>
          <%= number_to_currency(body.value, unit: "R$")  %>
        </td>
        <td>
          <%= link_to 'Detalhes', body, class: "btn btn-primary btn-sm text-light" %>
          <%= link_to 'Editar', edit_receivable_path(body), class: "btn btn-warning btn-sm text-light" %>
          <%= link_to 'Apagar', body, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm text-light" %>
        </td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="1">
      </td>
      <td>
        <h6> <b> Total </b> </h6>
      </td>
      <td colspan="3">
        <h6> <%= number_to_currency(receivable.last.sum(&:value), unit: "R$") %> </h6>
      </td>
    </tr>
    </tfoot>
  </table>
<% end %>

app/views/receivables/_form.html.erb
<%= simple_form_for(@receivable) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :value, value: number_with_precision(f.object.value, precision: 2) %>
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/receivables/_index.html.erb
<p id="notice"><%= notice %></p>

<%== pagy_bootstrap_nav(@calendar[:year]) %>
<%== pagy_bootstrap_nav(@calendar[:month]) %>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Value</th>
    <th>Date</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @receivables.each do |receivable| %>
    <tr>
      <td><%= receivable.title %></td>
      <td><%= receivable.description %></td>
      <td><%= number_to_currency(receivable.value, unit: "R$ ") %></td>
      <td><%= receivable.date %></td>
      <td><%= link_to 'Show', receivable %></td>
      <td><%= link_to 'Edit', edit_receivable_path(receivable) %></td>
      <td><%= link_to 'Destroy', receivable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/receivables/edit.html.erb
<h1>Editar Entrada</h1>

<%= render 'form', receivable: @receivable %>

<%= link_to 'Ver Entrada', @receivable, class: "btn btn-primary btn-sm text-light mt-2 float-right" %>
<%= link_to 'Entradas', receivables_path, class: "btn btn-secondary btn-sm text-light mt-2 float-right" %>

app/views/receivables/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col">
    <h3> Recebimentos - <%= number_to_currency(current_user.receivable_last_month, unit: "R$") %> </h3>
    <%= link_to 'New Receivable', new_receivable_path, class: "btn btn-primary btn-sm text-white" %>
    <%= link_to 'Voltar', root_path, class: "btn btn-primary btn-sm text-white" %>
  </div>
</div>
<hr />

<%= render "receivables/index" %>

app/views/receivables/new.html.erb
<h1>Nova Entrada</h1>

<%= render 'form', receivable: @receivable %>

<%= link_to 'Voltar', receivables_path, class: "btn btn-secondary btn-sm text-light mt-2 float-right" %>

app/views/receivables/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
  <tr>
    <th>Título</th>
    <th>Descrição</th>
    <th>Valor</th>
    <th>Data</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td> <%= @receivable.title %> </td>
    <td> <%= @receivable.description.nil? ? @receivable.description : "---" %> </td>
    <td> <%= @receivable.value %> </td>
    <td> <%= @receivable.date %> </td>
  </tr>
  </tbody>
</table>

<%= link_to 'Editar', edit_receivable_path(@receivable), class: "btn btn-warning btn-sm text-light" %>
<%= link_to 'Voltar', receivables_path, class: "btn btn-secondary btn-sm text-light" %>