config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users

  resources :payments
  resources :receivables
  resources :save_moneys do
    resources :save_money_wallets
  end
end

app/models/save_money.rb
class SaveMoney < ApplicationRecord
  belongs_to :user

  has_many :wallets, class_name: 'SaveMoneyWallet', dependent: :destroy

  accepts_nested_attributes_for :wallets, allow_destroy: true

  validates :title, presence: true

  def total_by_wallet
    ::SaveMoneys::Balance.new({ save_money: self }).call
  end
end

app/controllers/save_moneys_controller.rb
# frozen_string_literal: true

class SaveMoneysController < ApplicationController
  before_action :set_save_money, only: %i[show edit update destroy]

  # GET /save_moneys or /save_moneys.json
  def index
    @save_moneys = SaveMoney.where(user: current_user)
  end

  # GET /save_moneys/1 or /save_moneys/1.json
  def show; end

  # GET /save_moneys/new
  def new
    @save_money = SaveMoney.new
  end

  # GET /save_moneys/1/edit
  def edit; end

  # POST /save_moneys or /save_moneys.json
  def create
    @save_money = SaveMoney.new(user_save_money_params)

    respond_to do |format|
      if @save_money.save
        format.html { redirect_to @save_money, notice: 'Save money was successfully created.' }
        format.json { render :show, status: :created, location: @save_money }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @save_money.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /save_moneys/1 or /save_moneys/1.json
  def update
    respond_to do |format|
      if @save_money.update(save_money_params)
        format.html { redirect_to @save_money, notice: 'Save money was successfully updated.' }
        format.json { render :show, status: :ok, location: @save_money }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @save_money.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /save_moneys/1 or /save_moneys/1.json
  def destroy
    @save_money.destroy
    respond_to do |format|
      format.html { redirect_to save_moneys_url, notice: 'Save money was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_save_money
    @save_money = SaveMoney.where(user: current_user).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def save_money_params
    params.require(:save_money).permit(:title, :description,
                                       save_money_wallets_attributes: [:title, :description, :value, :date])
  end

  def user_save_money_params
    save_money_params.merge({ user: current_user })
  end
end

app/helpers/save_moneys_helper.rb
module SaveMoneysHelper
end

app/views/save_moneys/_form.html.erb
<%= simple_form_for(@save_money) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <form class="form-control">
    <div class="row">
      <div class="col-6 mb-2">
        <%= f.input :title,
                    required: true,
                    label: false,
                    input_html: { placeholder: "Título *" } %>
      </div>
      <div class="col-6 mb-2">
        <%= f.input :description,
                    label: false,
                    input_html: { placeholder: "Descrição", rows: 1 } %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Criar Carteira", class: "btn btn-success" %>
    </div>
  </form>
<% end %>

app/views/save_moneys/edit.html.erb
<h1>Editing Save Money</h1>

<%= render 'form', save_money: @save_money %>

<%= link_to 'Show', @save_money %> |
<%= link_to 'Back', save_moneys_path %>

app/views/save_moneys/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col">
    <h3> Dinheiro Guardado - <%= number_to_currency(current_user.total_balance_wallets, unit: "R$") %> </h3>
    <%= link_to 'Guardar Dinheiro', new_save_money_path, class: "btn btn-primary btn-sm text-white" %>
    <%= link_to 'Voltar', root_path, class: "btn btn-primary btn-sm text-white" %>
  </div>
</div>
<hr />

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th> Total </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @save_moneys.each do |save_money| %>
      <tr>
        <td> <%= save_money.title %> </td>
        <td> <%= save_money.description %> </td>
        <td> <%= number_to_currency(save_money.total_by_wallet, unit: "R$ ") %> </td>
        <td>
          <%= link_to 'Show', save_money %>
          <%= link_to 'Edit', edit_save_money_path(save_money) %>
          <%= link_to 'Destroy', save_money, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/save_moneys/new.html.erb
<h1>Nova Carteira</h1>

<%= render 'form', save_money: @save_money %>

<%= link_to 'Voltar', save_moneys_path, class: "btn btn-secondary btn-sm text-light mt-2 float-right" %>

app/views/save_moneys/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h2> Nova Entrada: </h2>
  <%= render "save_money_wallets/form" %>

  <div class="col-2 mt-2">
    <%= link_to "Voltar", save_moneys_path, class: "btn btn-primary text-white" %>
  </div>
</div>

<div>
  <h2>Reservas/Investimentos:</h2>
  <%= render "save_money_wallets/wallets" %>
</div>